title: NBNL Informatiemodellen
theme: just-the-docs
baseurl: /nbnl-conceptuele-informatiemodellen

collections:
  modellen:
    output: true

just_the_docs:
  collections:
    modellen:
      name: Modellen

nav_external_links:
  - title: Begrippenkader
    url: https://begrippen.netbeheernederland.nl

include:
  - "**/*.svg"

defaults:
  - scope:
      path: ""
    values:
      layout: default
