title: Stelsel van energieregisters
theme: just-the-docs
baseurl: /nbnl-conceptuele-informatiemodellen

collections:
  modellen:
    output: true

just_the_docs:
  collections:
    modellen:
      name: Registers

defaults:
  - scope:
      path: ""
    values:
      layout: default

color_scheme: nbnl
logo: "/assets/images/logo.svg"
fav_icon: "/assets/images/favicon.png"
